version: '3'
services:
  rabbitmq:
    image: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.8.1
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
  ipfs:
    image: ipfs/go-ipfs:v0.7.0
    ports:
      - 4001:4001
      - 5001:5001
      - 8080:8080
  ipfs-tika:
    build: https://github.com/ipfs-search/ipfs-tika.git
    ports:
      - 8081:8081
    depends_on:
      - ipfs
    environment:
      - IPFS_GATEWAY=http://ipfs:8080/
    deploy:
      restart_policy:
        condition: on-failure
  ipfs-crawler:
    build: .
    depends_on:
      - rabbitmq
      - elasticsearch
      - ipfs
      - ipfs-tika
    environment:
      - IPFS_TIKA_URL=http://ipfs-tika:8081
      - IPFS_API_URL=ipfs:5001
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - AMQP_URL=amqp://guest:guest@rabbitmq:5672/
    deploy:
      restart_policy:
        condition: on-failure
  ipfs-search-api:
    build: https://github.com/ipfs-search/ipfs-search-api.git#:server
    ports:
      - 9615:9615
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
  ipfs-sniffer:
    build: https://github.com/ipfs-search/ipfs-sniffer.git
    depends_on:
      - rabbitmq
    environment:
      - AMQP_URL=amqp://guest:guest@rabbitmq:5672/
    deploy:
      restart_policy:
        condition: on-failure
